const express = require('express');
const router = express.Router();
const supabase = require('../supabaseClient');

module.exports = (requireAuth, requireAdmin) => {
    // GET current user profile
    router.get('/me', requireAuth, async (req, res) => {
        const { data, error } = await supabase
            .from('users')
            .select('*')
            .eq('id', req.user.id)
            .single();

        if (error) return res.status(500).json({ error: error.message });
        res.json(data);
    });

    // UPDATE current user profile
    router.put('/me', requireAuth, async (req, res) => {
        const { first_name, last_name, phone } = req.body;
        const { data, error } = await supabase
            .from('users')
            .update({ first_name, last_name, phone })
            .eq('id', req.user.id)
            .select()
            .single();

        if (error) return res.status(500).json({ error: error.message });
        res.json(data);
    });

    // GET all users (Admin)
    router.get('/', requireAuth, requireAdmin, async (req, res) => {
        const { data, error } = await supabase
            .from('users')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) return res.status(500).json({ error: error.message });
        res.json(data);
    });

    // UPDATE a user (Admin)
    router.put('/:id', requireAuth, requireAdmin, async (req, res) => {
        const { id } = req.params;
        const { first_name, last_name, phone, is_admin } = req.body;
        const { data, error } = await supabase
            .from('users')
            .update({ first_name, last_name, phone, is_admin })
            .eq('id', id)
            .select()
            .single();

        if (error) return res.status(500).json({ error: error.message });
        res.json(data);
    });

    // DELETE a user (Admin)
    router.delete('/:id', requireAuth, requireAdmin, async (req, res) => {
        const { id } = req.params;
        
        // Delete from auth (using service role key usually, but since we are mocking auth integration for now,
        // we will at least delete from our public `users` table which cascades)
        const { error } = await supabase
            .from('users')
            .delete()
            .eq('id', id);

        if (error) return res.status(500).json({ error: error.message });
        res.status(204).send();
    });

    // REGISTER a new user (Public endpoint to sync Supabase Auth -> users table)
    router.post('/sync', async (req, res) => {
        const { id, email, first_name, last_name, phone } = req.body;
        // id should be the UUID generated by Supabase Auth
        const { data, error } = await supabase
            .from('users')
            .insert([{ id, email, first_name, last_name, phone }])
            .select()
            .single();

        if (error) return res.status(500).json({ error: error.message });
        res.status(201).json(data);
    });

    return router;
};
